### ISSUE TITLE
Old search attached

### ISSUE THREAD

**Issue by teetparts** [Edicy/design-buenosaires#2] opened 2015-01-15 13:52 UTC

**Comment by kaspar-naaber** [comment] 2015-01-21 13:56
Couldn't reproduce. Maybe the template was not synchronized with the GitHub while testing? Reopen if the issue is still present.

**Comment by kaspar-naaber** [comment] 2015-01-21 14:38
Was still present. Fixed in 3a2860ab933cc85af2f59c059489a64852eb31a6

**Closed as completed by kaspar-naaber** 2015-01-21 14:38 UTC
